# Configuration for Gitlab-CI.
# Builds appear on https://gitlab.com/buildroot.org/buildroot/pipelines

image: $CI_REGISTRY/buildroot.org/buildroot/base:20230207.1123

stages:
  - generate-gitlab-ci
  - build

generate-gitlab-ci-yml:
  stage: generate-gitlab-ci
  script: ./support/scripts/generate-gitlab-ci-yml support/misc/gitlab-ci.yml.in > generated-gitlab-ci.yml
  artifacts:
    when: always
    artifacts:
        paths:        
            - logs/
        expire_in: 2 weeks
    script:
        - echo "Capturing Pipeline logs"    

########################
# Source Jobs (per-platform)
########################

source_zynq:
    <<: *source_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zed

source_socfpga:
    <<: *source_job_template
    variables:
        CONFIG_JOB_PLATFORM: socfpga
        CONFIG_JOB_BOARD: sockit

source_zynqmp:
    <<: *source_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynqmp
        CONFIG_JOB_BOARD: zcu102

########################
# Sysroot Jobs (per-platform)
########################

sysroot_zynq:
    <<: *sysroot_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zed

sysroot_socfpga:
    <<: *sysroot_job_template
    variables:
        CONFIG_JOB_PLATFORM: socfpga
        CONFIG_JOB_BOARD: sockit

sysroot_zynqmp:
    <<: *sysroot_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynqmp
        CONFIG_JOB_BOARD: zcu102

########################
# Build Jobs (per-board)
########################

build_zybo:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zybo

build_zed:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zed

build_zc706:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zc706

build_zc702:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zc702

build_sockit:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: socfpga
        CONFIG_JOB_BOARD: sockit

build_alteracycv:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: socfpga
        CONFIG_JOB_BOARD: alteracycv

build_zcu102:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynqmp
        CONFIG_JOB_BOARD: zcu102

=======
# Configuration for Gitlab-CI.
# Builds appear on https://gitlab.com/buildroot.org/buildroot/pipelines

image: $CI_REGISTRY/buildroot.org/buildroot/base:20230207.1123

stages:
  - generate-gitlab-ci
  - build

generate-gitlab-ci-yml:
  stage: generate-gitlab-ci
  script: ./support/scripts/generate-gitlab-ci-yml support/misc/gitlab-ci.yml.in > generated-gitlab-ci.yml
  artifacts:
    when: always
    paths:
      - generated-gitlab-ci.yml
      - br-test-pkg/*/.config
      - br-test-pkg/*/missing.config

buildroot-pipeline:
  stage: build
  trigger:
    include:
      - artifact: generated-gitlab-ci.yml
        job: generate-gitlab-ci-yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
>>>>>>> c9946b4d21c1883c30f2b1f62fc6601ca16b6c99
