#!/bin/sh
#
# Starts the inetd daemon.
#

NAME=inetd
DAEMON=/usr/sbin/$NAME

case "$1" in
	start)
		echo -n "Starting $NAME: "
		start-stop-daemon -S -q -x $DAEMON && echo "OK" || echo "Failed"
		;;
	stop)
		echo -n "Stopping $NAME: "
		start-stop-daemon -K -q -n $NAME && echo "OK" || echo "Failed"
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo $"Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
