#!/bin/sh
#
# Copy the network scripts from the boot device
#

source /etc/bootvars.conf

source /etc/init.d/start_only.sh

if [ "$_SYS_PERSISTENT_FILESYSTEM" == "true" ]; then
    UPDATE=mv
    WARN_NOTFOUND=false
else
    UPDATE=cp
    WARN_NOTFOUND=true
fi

for i in $(seq 1 $_NETWORK_FILES_NELEM); do
	src=${_SD_ROOT}/$(get_elem $i $_NETWORK_SRC_FILES)
	dst=$(get_elem $i $_NETWORK_DST_FILES)
	warn=$(get_elem $i $_NETWORK_REQ_FILES)
	if [ -f $src ]; then
    	echo "+++ Configuring $dst"
	    $UPDATE -f $src $dst
	elif  [ "$WARN_NOTFOUND" == "true" ] && [ "$warn" == "true" ]; then
    	echo "### $src file not found in the SD card. Using default settings in $dst..."
	fi
done

