#!/bin/sh
#
# Mount the SD card and run the init.sh script
#

case "$1" in
	start)
		echo "running sd card init.sh"
		if [ -f /mnt/init.sh ]; then
			/mnt/init.sh
		fi
		;;
	stop)
		# do nothing
		;;
	restart | reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?