#!/bin/sh
# Set uboot to use a new devicetree when booting
# Syntax fw_setdevicetree <new dtb>

NEWDT=$1
DT_DIR=/mnt
DT_VAR=devicetree_image

# Make sure the specified file exists
if [ ! -e ${DT_DIR}/${NEWDT} ]; then
	echo "ERROR: Devicetree '${NEWDT}' does not exist"
	exit 1
fi

fw_setenv ${DT_VAR} ${NEWDT}

