#!/bin/sh
# Set a variable in the firmware
# Syntax: fw_setvar <var> <value>

NEWVAL=$2
FWVAR=$1
DUMMY_VAR=xxx_dummy_xxx
UBOOT_ENV=/mnt/uboot.env
UBOOT_ENV_SIZE=128k

# If the environment does not exist, create a default file
if [ ! -e ${UBOOT_ENV} ]; then
	dd if=/dev/zero of=${UBOOT_ENV} bs=${UBOOT_ENV_SIZE} count=1 &> /dev/null
	fw_setenv ${DUMMY_VAR} 1234 &> /dev/null
	fw_setenv ${DUMMY_VAR}
	sync
fi

fw_setenv ${FWVAR} ${NEWVAL}
sync
