################################################################################
#
# Xilinx U-Boot Modifications
#
################################################################################

UBOOT_XILINX_INSTALL_TARGET = NO
UBOOT_XILINX_INSTALL_IMAGES = NO


UBOOT_XILINX_VIVADO_HANDOFF_DIR = $(call qstrip,$(BR2_PACKAGE_UBOOT_XILINX_VIVADO_HANDOFF_DIR))
UBOOT_XILINX_UBOOT_TARGET_DIR = $(call qstrip,$(BR2_PACKAGE_UBOOT_XILINX_UBOOT_TARGET_DIR))

UBOOT_XILINX_UBOOT_DIR = uboot-$(UBOOT_VERSION)
UBOOT_XILINX_UBOOT_BUILD_DIR = $(BUILD_DIR)/$(UBOOT_XILINX_UBOOT_DIR)
UBOOT_XILINX_UBOOT_UPDATE_DIR = $(UBOOT_XILINX_UBOOT_BUILD_DIR)/$(UBOOT_XILINX_UBOOT_TARGET_DIR)


define UBOOT_XILINX_UPDATE_UBOOT
    @echo ">>> Copying handoff files from $(UBOOT_XILINX_VIVADO_HANDOFF_DIR)"
    cp -R -f $(UBOOT_XILINX_VIVADO_HANDOFF_DIR)/* $(UBOOT_XILINX_UBOOT_UPDATE_DIR)/
endef

ifeq ($(BR2_PACKAGE_UBOOT_XILINX),y)
UBOOT_PRE_CONFIGURE_HOOKS += UBOOT_XILINX_UPDATE_UBOOT
UBOOT_DEPENDENCIES += uboot-xilinx
endif

$(eval $(generic-package))
