#ifndef __ADI_MW_AXISTREAM_DMA__
#define __ADI_MW_AXISTREAM_DMA__

#if defined(MW_DATAWIDTH_SELECT) && MW_DATAWIDTH_SELECT == 256
	#define ADI_MM2S_DATAWIDTH <0x100>
	#define ADI_S2MM_DATAWIDTH <0x100>
#elif defined(MW_DATAWIDTH_SELECT) && MW_DATAWIDTH_SELECT == 128
	#define ADI_MM2S_DATAWIDTH <0x80>
	#define ADI_S2MM_DATAWIDTH <0x80>
#elif defined(MW_DATAWIDTH_SELECT) && MW_DATAWIDTH_SELECT == 64
	#define ADI_MM2S_DATAWIDTH <0x40>
	#define ADI_S2MM_DATAWIDTH <0x40>
#else
	#define ADI_MM2S_DATAWIDTH <0x20>
	#define ADI_S2MM_DATAWIDTH <0x20>
#endif

#if defined(MW_AXI_MM_DATAWIDTH_SELECT) && MW_AXI_MM_DATAWIDTH_SELECT == 128
	#define ADI_AXI_MM_DATAWIDTH <0x80>
#else
	#define ADI_AXI_MM_DATAWIDTH <0x40>
#endif

#define ADI_AXI_DMAC_TYPE_AXI_MM <0>
#define ADI_AXI_DMAC_TYPE_AXI_STREAM <1>
#define ADI_AXI_DMAC_TYPE_AXI_FIFO <2>

#endif /* __ADI_MW_AXISTREAM_DMA__ */
