#!/bin/sh
#
# Copy the network scripts from the boot device
#

source /etc/bootvars.conf

if [ "$1" == "" ]; then
    BACKUP_DIR=${_SD_ROOT}
else
    BACKUP_DIR=$1
fi

if [ "$2" == "" ]; then
    SRC="system"
else
    SRC=$2
fi


mkdir -p $BACKUP_DIR

SD_KEYDIR=${BACKUP_DIR}/sshkeys
ETC_KEYDIR=/etc/ssh
mkdir -p $SD_KEYDIR

echo "Backing up network configuration..."  

if [ "$SRC" == "system" ]; then
    cp -f /etc/hostname ${BACKUP_DIR}/hostname
    cp -f /etc/network/interfaces ${BACKUP_DIR}/interfaces
    cp $ETC_KEYDIR/ssh_host_*key* $SD_KEYDIR/
else
    cp -f ${SRC}/hostname ${BACKUP_DIR}/hostname
    cp -f ${SRC}/interfaces ${BACKUP_DIR}/interfaces
    cp ${SRC}/sshkeys/ssh_host_*key* $SD_KEYDIR/
fi

sync


