################################################################################
#
# uboot altera
#
################################################################################

UBOOT_ALTERA_VERSION = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_VERSION))
UBOOT_ALTERA_BOARD_NAME = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_BOARDNAME))

UBOOT_ALTERA_LICENSE = GPLv2+
UBOOT_ALTERA_LICENSE_FILES = Licenses/gpl-2.0.txt

UBOOT_ALTERA_INSTALL_IMAGES = YES

ifeq ($(UBOOT_ALTERA_VERSION),custom)
# Handle custom U-Boot tarballs as specified by the configuration
UBOOT_ALTERA_TARBALL = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_TARBALL_LOCATION))
UBOOT_ALTERA_SITE = $(patsubst %/,%,$(dir $(UBOOT_ALTERA_TARBALL)))
UBOOT_ALTERA_SOURCE = $(notdir $(UBOOT_ALTERA_TARBALL))
BR_NO_CHECK_HASH_FOR += $(UBOOT_ALTERA_SOURCE)
else ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_GIT),y)
UBOOT_ALTERA_SITE = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_REPO_URL))
UBOOT_ALTERA_SITE_METHOD = git
else ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_HG),y)
UBOOT_ALTERA_SITE = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_REPO_URL))
UBOOT_ALTERA_SITE_METHOD = hg
else
# Handle stable official U-Boot versions
UBOOT_ALTERA_SITE = ftp://ftp.denx.de/pub/u-boot
UBOOT_ALTERA_SOURCE = u-boot-$(UBOOT_ALTERA_VERSION).tar.bz2
ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_VERSION),y)
BR_NO_CHECK_HASH_FOR += $(UBOOT_ALTERA_SOURCE)
endif
endif

ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_ELF),y)
UBOOT_ALTERA_BIN = u-boot
else ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_KWB),y)
UBOOT_ALTERA_BIN = u-boot.kwb
UBOOT_ALTERA_MAKE_TARGET = $(UBOOT_ALTERA_BIN)
else ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_AIS),y)
UBOOT_ALTERA_BIN = u-boot.ais
UBOOT_ALTERA_MAKE_TARGET = $(UBOOT_ALTERA_BIN)
else ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_LDR),y)
UBOOT_ALTERA_BIN = u-boot.ldr
else ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_NAND_BIN),y)
UBOOT_ALTERA_BIN = u-boot-nand.bin
else ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_IMG),y)
UBOOT_ALTERA_BIN = u-boot.img
else ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_IMX),y)
UBOOT_ALTERA_BIN = u-boot.imx
else ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_SB),y)
UBOOT_ALTERA_BIN = u-boot.sb
UBOOT_ALTERA_MAKE_TARGET = $(UBOOT_ALTERA_BIN)
UBOOT_ALTERA_DEPENDENCIES += host-elftosb
else ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_SD),y)
# BootStream (.sb) is generated by U-Boot, we convert it to SD format
UBOOT_ALTERA_BIN = u-boot.sd
UBOOT_ALTERA_MAKE_TARGET = u-boot.sb
UBOOT_ALTERA_DEPENDENCIES += host-elftosb
else ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_CUSTOM),y)
UBOOT_ALTERA_BIN = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_CUSTOM_NAME))
else
UBOOT_ALTERA_BIN = u-boot.bin
UBOOT_ALTERA_BIN_IFT = $(UBOOT_ALTERA_BIN).ift
endif

ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_SPL_PRELOADER),y)
UBOOT_ALTERA_MKPIMAGE = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_MKPIMAGE_PATH))
UBOOT_ALTERA_SPL_BIN = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_SPL_NAME))
UBOOT_ALTERA_PRELOADER_BIN = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_SPL_PRELOADER_NAME))
endif

UBOOT_ALTERA_ARCH = $(KERNEL_ARCH)

UBOOT_ALTERA_MAKE_OPTS += \
	CROSS_COMPILE="$(CCACHE) $(TARGET_CROSS)" \
	ARCH=$(UBOOT_ALTERA_ARCH)

# Helper function to fill the U-Boot config.h file.
# Argument 1: option name
# Argument 2: option value
# If the option value is empty, this function does nothing.
define insert_define
$(if $(call qstrip,$(2)),
	@echo "#ifdef $(strip $(1))" >> $(@D)/include/config.h
	@echo "#undef $(strip $(1))" >> $(@D)/include/config.h
	@echo "#endif" >> $(@D)/include/config.h
	@echo '#define $(strip $(1)) $(call qstrip,$(2))' >> $(@D)/include/config.h)
endef

# prior to u-boot 2013.10 the license info was in COPYING. Copy it so
# legal-info finds it
define UBOOT_ALTERA_COPY_OLD_LICENSE_FILE
	if [ -f $(@D)/COPYING ]; then \
		$(INSTALL) -m 0644 -D $(@D)/COPYING $(@D)/Licenses/gpl-2.0.txt; \
	fi
endef

UBOOT_ALTERA_POST_EXTRACT_HOOKS += UBOOT_ALTERA_COPY_OLD_LICENSE_FILE


# Copy config files generated from Quartus / EDS
ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_UPDATE_FILES),y)

ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_UPDATE_FILE_SRC_CUSTOM),y)

# Use custom files for updating the source
UBOOT_ALTERA_EDS_GENERATED_DIR = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_EDS_GENERATED_DIR))/generated
UBOOT_ALTERA_QUARTUS_HANDOFF_DIR = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_QUARTUS_HANDOFF_DIR))

else
# use files generated by the Altera Preloader package
UBOOT_ALTERA_DEPENDENCIES += altera-preloader

UBOOT_ALTERA_EDS_GENERATED_DIR = $(STAGING_DIR)/usr/share/altera-preloader/generated
UBOOT_ALTERA_QUARTUS_HANDOFF_DIR = $(STAGING_DIR)/usr/share/altera-preloader/handoff

endif

# Copy the Quartus Handoff Files
ifneq ($(UBOOT_ALTERA_QUARTUS_HANDOFF_DIR),)
define UBOOT_ALTERA_COPY_HANDOFF_FILES
    @echo ">>> Copying board files from $(UBOOT_ALTERA_QUARTUS_HANDOFF_DIR)"
    cp -R -f $(UBOOT_ALTERA_QUARTUS_HANDOFF_DIR)/* $(@D)/board/altera/socfpga/sdram
endef
UBOOT_ALTERA_PRE_CONFIGURE_HOOKS += UBOOT_ALTERA_COPY_HANDOFF_FILES
endif

# Copy the EDS generated files
ifneq ($(UBOOT_ALTERA_EDS_GENERATED_DIR),)
define UBOOT_ALTERA_COPY_EDS_FILES
    @echo ">>> Copying board files from $(UBOOT_ALTERA_EDS_GENERATED_DIR)"
    cp -R -f $(UBOOT_ALTERA_EDS_GENERATED_DIR)/* $(@D)/board/altera/socfpga
endef
UBOOT_ALTERA_PRE_CONFIGURE_HOOKS += UBOOT_ALTERA_COPY_EDS_FILES
endif

endif

# Prior to Buildroot 2015.05, only patch directories were supported. New
# configurations use BR2_PACKAGE_UBOOT_ALTERA_PATCH instead.
ifneq ($(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_PATCH_DIR)),)
define UBOOT_ALTERA_APPLY_CUSTOM_PATCHES
	$(APPLY_PATCHES) $(@D) $(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_PATCH_DIR) \*.patch
endef

UBOOT_ALTERA_POST_PATCH_HOOKS += UBOOT_ALTERA_APPLY_CUSTOM_PATCHES
endif

# Analogous code exists in linux/linux.mk. Basically, the generic
# package infrastructure handles downloading and applying remote
# patches. Local patches are handled depending on whether they are
# directories or files.
UBOOT_ALTERA_PATCHES = $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_PATCH))
UBOOT_ALTERA_PATCH = $(filter ftp://% http://% https://%,$(UBOOT_ALTERA_PATCHES))

define UBOOT_ALTERA_APPLY_LOCAL_PATCHES
	for p in $(filter-out ftp://% http://% https://%,$(UBOOT_ALTERA_PATCHES)) ; do \
		if test -d $$p ; then \
			$(APPLY_PATCHES) $(@D) $$p \*.patch || exit 1 ; \
		else \
			$(APPLY_PATCHES) $(@D) `dirname $$p` `basename $$p` || exit 1; \
		fi \
	done
endef
UBOOT_ALTERA_POST_PATCH_HOOKS += UBOOT_ALTERA_APPLY_LOCAL_PATCHES

define UBOOT_ALTERA_CONFIGURE_CMDS
	$(TARGET_CONFIGURE_OPTS) 	\
		$(MAKE) -C $(@D) $(UBOOT_ALTERA_MAKE_OPTS)		\
		$(UBOOT_ALTERA_BOARD_NAME)_config
	@echo >> $(@D)/include/config.h
	@echo "/* Add a wrapper around the values Buildroot sets. */" >> $(@D)/include/config.h
	@echo "#ifndef __BR2_ADDED_CONFIG_H" >> $(@D)/include/config.h
	@echo "#define __BR2_ADDED_CONFIG_H" >> $(@D)/include/config.h
	$(call insert_define,DATE,$(DATE))
	$(call insert_define,CONFIG_LOAD_SCRIPTS,1)
	$(call insert_define,CONFIG_IPADDR,$(BR2_PACKAGE_UBOOT_ALTERA_IPADDR))
	$(call insert_define,CONFIG_GATEWAYIP,$(BR2_PACKAGE_UBOOT_ALTERA_GATEWAY))
	$(call insert_define,CONFIG_NETMASK,$(BR2_PACKAGE_UBOOT_ALTERA_NETMASK))
	$(call insert_define,CONFIG_SERVERIP,$(BR2_PACKAGE_UBOOT_ALTERA_SERVERIP))
	$(call insert_define,CONFIG_ETHADDR,$(BR2_PACKAGE_UBOOT_ALTERA_ETHADDR))
	$(call insert_define,CONFIG_ETH1ADDR,$(BR2_PACKAGE_UBOOT_ALTERA_ETH1ADDR))
	@echo "#endif /* __BR2_ADDED_CONFIG_H */" >> $(@D)/include/config.h
endef

define UBOOT_ALTERA_BUILD_CMDS
	$(TARGET_CONFIGURE_OPTS) 	\
		$(MAKE) -C $(@D) $(UBOOT_ALTERA_MAKE_OPTS) 		\
		$(UBOOT_ALTERA_MAKE_TARGET)
	$(if $(BR2_PACKAGE_UBOOT_ALTERA_FORMAT_SD),
		$(@D)/tools/mxsboot sd $(@D)/u-boot.sb $(@D)/u-boot.sd)
    $(if $(BR2_PACKAGE_UBOOT_ALTERA_SPL_PRELOADER),
        $(UBOOT_ALTERA_MKPIMAGE) --header-version 0 \
        -o $(@D)/$(UBOOT_ALTERA_PRELOADER_BIN) $(@D)/$(UBOOT_ALTERA_SPL_BIN) \
        $(@D)/$(UBOOT_ALTERA_SPL_BIN) $(@D)/$(UBOOT_ALTERA_SPL_BIN) \
        $(@D)/$(UBOOT_ALTERA_SPL_BIN))

endef

define UBOOT_ALTERA_BUILD_OMAP_IFT
	$(HOST_DIR)/usr/bin/gpsign -f $(@D)/u-boot.bin \
		-c $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_OMAP_IFT_CONFIG))
endef

define UBOOT_ALTERA_INSTALL_IMAGES_CMDS
	cp -dpf $(@D)/$(UBOOT_ALTERA_BIN) $(BINARIES_DIR)/
	$(if $(BR2_PACKAGE_UBOOT_ALTERA_SPL),
		cp -dpf $(@D)/$(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_SPL_NAME)) $(BINARIES_DIR)/)
    $(if $(BR2_PACKAGE_UBOOT_ALTERA_SPL_PRELOADER),
		cp -dpf $(@D)/$(UBOOT_ALTERA_PRELOADER_BIN) $(BINARIES_DIR)/)
	$(if $(BR2_PACKAGE_UBOOT_ALTERA_ENVIMAGE),
		$(HOST_DIR)/usr/bin/mkenvimage -s $(BR2_PACKAGE_UBOOT_ALTERA_ENVIMAGE_SIZE) \
		$(if $(BR2_PACKAGE_UBOOT_ALTERA_ENVIMAGE_REDUNDANT),-r) \
		-o $(BINARIES_DIR)/uboot-env.bin $(BR2_PACKAGE_UBOOT_ALTERA_ENVIMAGE_SOURCE))
endef

define UBOOT_ALTERA_INSTALL_OMAP_IFT_IMAGE
	cp -dpf $(@D)/$(UBOOT_ALTERA_BIN_IFT) $(BINARIES_DIR)/
endef

ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_OMAP_IFT),y)
ifeq ($(BR_BUILDING),y)
ifeq ($(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_OMAP_IFT_CONFIG)),)
$(error No gpsign config file. Check your BR2_PACKAGE_UBOOT_ALTERA_OMAP_IFT_CONFIG setting)
endif
ifeq ($(wildcard $(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_OMAP_IFT_CONFIG))),)
$(error gpsign config file $(BR2_PACKAGE_UBOOT_ALTERA_OMAP_IFT_CONFIG) not found. Check your BR2_PACKAGE_UBOOT_ALTERA_OMAP_IFT_CONFIG setting)
endif
endif
UBOOT_ALTERA_DEPENDENCIES += host-omap-u-boot-utils
UBOOT_ALTERA_POST_BUILD_HOOKS += UBOOT_ALTERA_BUILD_OMAP_IFT
UBOOT_ALTERA_POST_INSTALL_IMAGES_HOOKS += UBOOT_ALTERA_INSTALL_OMAP_IFT_IMAGE
endif

ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_ENVIMAGE),y)
ifeq ($(BR_BUILDING),y)
ifeq ($(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_ENVIMAGE_SOURCE)),)
$(error Please define a source file for Uboot environment (BR2_PACKAGE_UBOOT_ALTERA_ENVIMAGE_SOURCE setting))
endif
ifeq ($(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_ENVIMAGE_SIZE)),)
$(error Please provide Uboot environment size (BR2_PACKAGE_UBOOT_ALTERA_ENVIMAGE_SIZE setting))
endif
endif
UBOOT_ALTERA_DEPENDENCIES += host-uboot-tools
endif

$(eval $(generic-package))

ifeq ($(BR2_PACKAGE_UBOOT_ALTERA)$(BR_BUILDING),yy)
ifeq ($(UBOOT_ALTERA_BOARD_NAME),)
$(error No U-Boot board name set. Check your BR2_PACKAGE_UBOOT_ALTERA_BOARDNAME setting)
endif

ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_VERSION),y)
ifeq ($(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_VERSION_VALUE)),)
$(error No custom U-Boot version specified. Check your BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_VERSION_VALUE setting)
endif # qstrip BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_VERSION_VALUE
endif # BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_VERSION

ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_TARBALL),y)
ifeq ($(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_TARBALL_LOCATION)),)
$(error No custom U-Boot tarball specified. Check your BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_TARBALL_LOCATION setting)
endif # qstrip BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_TARBALL_LOCATION
endif # BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_TARBALL

ifeq ($(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_GIT)$(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_HG),y)
ifeq ($(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_REPO_URL)),)
$(error No custom U-Boot repository URL specified. Check your BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_REPO_URL setting)
endif # qstrip BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_CUSTOM_REPO_URL
ifeq ($(call qstrip,$(BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_REPO_VERSION)),)
$(error No custom U-Boot repository URL specified. Check your BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_REPO_VERSION setting)
endif # qstrip BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_CUSTOM_REPO_VERSION
endif # BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_GIT || BR2_PACKAGE_UBOOT_ALTERA_CUSTOM_HG

endif # BR2_PACKAGE_UBOOT_ALTERA && BR_BUILDING
